ALTER TABLE "worker" ADD COLUMN port INTEGER;
UPDATE "worker" SET port=8080 WHERE id IS NOT NULL;
ALTER TABLE "worker" ALTER COLUMN port SET NOT NULL;
ALTER TABLE "worker" ALTER COLUMN port SET DEFAULT 8080;